require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Api::V1::RecipesController, :type => :controller do

  let(:valid_attributes) { Fabricate.build(:recipe).attributes }
  let(:invalid_attributes) { {id: false, name: nil, nothing: 'here'} }

  before :each do
    request.accept = "application/json"
  end

  describe "GET index" do
    it "assigns all recipes as @recipes" do
      recipe = Fabricate(:recipe)
      get :index
      expect(assigns(:recipes)).to include(recipe)
    end
  end

  describe "GET show" do
    it "assigns the requested recipe as @recipe" do
      recipe = Fabricate(:recipe)
      get :show, {:id => recipe.to_param}
      expect(assigns(:recipe)).to eq(recipe)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Recipe" do
        expect {
          post :create, {:recipe => valid_attributes}
        }.to change(::Recipe, :count).by(1)
      end

      it "assigns a newly created recipe as @recipe" do
        post :create, {:recipe => valid_attributes}
        expect(assigns(:recipe)).to be_a(::Recipe)
        expect(assigns(:recipe)).to be_persisted
      end

      it "returns :created http status" do
        post :create, {:recipe => valid_attributes}
        expect(response).to have_http_status(:created)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved recipe as @recipe" do
        post :create, {:recipe => invalid_attributes}
        expect(assigns(:recipe)).to be_a_new(::Recipe)
      end

      it "returns :unprocessable_entity status" do
        post :create, {:recipe => {a: false}}
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        Fabricate.build(:recipe).attributes
      }

      it "updates the requested recipe" do
        recipe = Fabricate(:recipe)
        put :update, {:id => recipe.to_param, :recipe => new_attributes}
        recipe.reload
        expect(response).to have_http_status(:ok)
      end

      it "assigns the requested recipe as @recipe" do
        recipe = Fabricate(:recipe)
        put :update, {:id => recipe.to_param, :recipe => valid_attributes}
        expect(assigns(:recipe)).to eq(recipe)
      end

      it "returns :ok http status" do
        recipe = Fabricate(:recipe)
        put :update, {:id => recipe.to_param, :recipe => valid_attributes}
        expect(response).to have_http_status(:ok)
      end
    end

    describe "with invalid params" do
      it "assigns the recipe as @recipe" do
        recipe = Fabricate(:recipe)
        put :update, {:id => recipe.to_param, :recipe => invalid_attributes}
        expect(assigns(:recipe)).to eq(recipe)
      end

      it "returns :unprocessable_entity http status" do
        recipe = Fabricate(:recipe)
        put :update, {:id => recipe.to_param, :recipe => invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested recipe" do
      recipe = Fabricate(:recipe)
      expect {
        delete :destroy, {:id => recipe.to_param}
      }.to change(::Recipe, :count).by(-1)
    end

    it "redirects to the recipe list" do
      recipe = Fabricate(:recipe)
      delete :destroy, {:id => recipe.to_param}
      expect(response).to have_http_status(:no_content)
    end
  end

end
